### ISSUE TITLE
icons should be white instead of black

### ISSUE THREAD

**Issue by TeutonJon78** [acidhax/chromecast-audio-stream#13]
With the current icons being black, then are near invisible on the W10 taskbar. Moving them to white would help with visibility.

**Comment by gaussey** [comment]
Start>Settings > Personalisation > Colours

**Comment by TeutonJon78** [comment]
Sure, it can be changed, but the default taskbar is black, and the default W10 systray icons are ALL white.

**Comment by matbeedotcom** [comment]
Interesting, ok...

**Comment by ghost** [comment]
Solution:

Just replace the PNG files in the directory. Here are the files that need to be replaced in the main folder. 
![cast](https://cloud.githubusercontent.com/assets/17672952/14405483/0fe4d9de-fe90-11e5-8e20-eb2418377ded.png)
![cast-connected](https://cloud.githubusercontent.com/assets/17672952/14405482/0fe4c19c-fe90-11e5-8272-ee5abf8f4bbc.png)

Hope that it helped... however I figur that you already find out by yourself :smile:

**Comment by timo41** [comment]
Here are the files with inverted colors. I can see the icon now, but sadly the app doesn't work on my win 10 64bit pc.
You can't see them because they are infront of a white background (of the homepage). Just klick on them
|
v
![cast](https://cloud.githubusercontent.com/assets/19531506/15470260/e645bc7e-20ef-11e6-846e-f52a848563a1.png)
![cast-connected](https://cloud.githubusercontent.com/assets/19531506/15470261/e75304dc-20ef-11e6-88e2-bc2ad1845c64.png)

**Comment by matbeedotcom** [comment]
Integrating icons in update
