### ISSUE TITLE
Audio delay problem

### ISSUE THREAD

**Issue by PrabhuArchi** [acidhax/chromecast-audio-stream#37]
There is so much of delay in audio playback w.r.t. video playback. How to cope up with this issue? Please help!!

**Comment by EricTousignant** [comment]
Hello, I did also notice this issue. I have about 3 to 3.5 seconds delay.

I do not have an issue with it for now since I use it for audio only (music), but this is obviously unusable for content that needs to be in sync (like the audio from a movie).

@acidhax, do you have any idea where the delay is introduced?
If you give me some clue I'll try to take a look in the code.

Have a great day.

**Comment by matbeedotcom** [comment]
I think the delay is in 3 places. One- the driver I'm using is buffering data. Two- The network has inherent latency. Three- The Chromecast is also buffering data before playing.

**Comment by mcprat** [comment]
Just by the nature of "capturing" the audio instead of just redirecting, it will always have a larger delay. The audio has to be encoded and decoded _after_ original audio output is made. This requires processing power so unless you have a supercomputer I don't think this method will ever reach a delay less than 1 or 2 seconds.
