### ISSUE TITLE
Volume mixer needed

### ISSUE THREAD

**Issue by NessunoIM** [acidhax/chromecast-audio-stream#39]
Would be very useful to introduce a simply GUI to introduce a volume mixer such as Windows 10 (7,8 etc..) to have separated audio sources. For example if I listen (from my stereo system + chromecast audio) a song from youtube on firefox, I don't want listen an other sound, for example a video on VLC player on my chromecast but I want to lissen this video only with my pc speakers.

Sorry for my english.

![audddui](https://cloud.githubusercontent.com/assets/19640640/15638067/28656402-261c-11e6-954f-0f40ae218469.jpg)

**Comment by matbeedotcom** [comment]
Yeah, that'd be a good idea. I wonder how I could isolate per-application sound...

**Comment by Andulien** [comment]
Can this be reopened, or will this not be looked into anymore?

**Comment by mcprat** [comment]
It's really not likely because of how difficult it is. The application takes audio from the "hardware" level, aka the audio device through DirectSound, which is seen on the software level as the "default playback device". In this way, what the app does is the same as what the recording device "Stereo Mix" does, which also has a small delay and no ability to differentiate between the sources because it is already "mixed" into one channel.

**Comment by NessunoIM** [comment]
I've found this https://www.rogueamoeba.com/airfoil/windows/, I think could be useful for this purpouse.
It can be an inspiration for found a solution.
Sorry for have reopened the issue and thank you for your work.
