### ISSUE TITLE
Problems solved by registry hack (Windows 10)

### ISSUE THREAD

**Issue by drjp69** [acidhax/chromecast-audio-stream#52]
I first downloaded the app to my Downloads folder and ran it from there. It ran fine, and the app did exactly what I needed.

I then copied the app to a more permanent location. Again, it worked fine first time. When I next came to use it again, it connected to Chromecast but there was no audio—a problem I see others have had. I have tried it in several different folder locations with the same problem.

Last night I noted two further features:
(1)  The app worked fine from another location if there was a copy of the app present in the Downloads folder.
(2)  I was unable to delete the copy in Downloads while the app was running from another location.
Both suggested to me that the app was using one or more of the files in Downloads, even though I was running it from a different location.

Finding nothing in the app itself that would cause that, I searched the registry and found the following key:
HKEY_USERS\S-1-5-21- ... -1001\SOFTWARE\Classes\Wow6432Node\CLSID\ {8E14549B-DB61-4309-AFA1-3578E927E935}\InprocServer32
The value for (Default) was:
C:\Users\ ... \Downloads\audio-cast-1.0.0-win32-ia32\resources\bin\driver\win32\audio_sniffer.dll

Having changed that value to reflect the current location of the file, all seems to be working well.

You edit your own registry at your own risk, but this change might be worth trying for those having similar problems.

**Comment by Andulien** [comment]
Hey there, I just checked your fix, but it does not work for me. There is no Registry entry pointing to the audio sniffer, so there is nothing that can be updated. (win 10 64bit & kompatibility mode tested). Sadly this is not a fix for all.

**Comment by bluesodium** [comment]
doesn't work for me either. Windows 10 64 bit.

**Comment by xamonline** [comment]
worked fine for me until i also tired to move the files.  i tried extracting to the permanent location when that didn't work and still was unable to delete the original extracted files.  i found the sniffer file in the registry and successfully pointed to the new location.  at that point i was able to delete the original download files, however, the casting no longer worked (rather, i heard a connect noise through the cast, but, audio was no longer streaming to the cast.)  i have since reinstalled the files in the download location, updated the registry file, and the problem remains.  i've removed all files and tried a fresh install and now i can no longer get it to work (still hear the connecting noise but that's all). not sure what to try now.

**Comment by drjp69** [comment]
@xamonline Have you restarted the computer?

**Comment by xamonline** [comment]
i did.  i restored my registry as well.  i found that the firewall was blocking so i added exceptions but it still wasn't working.  having same issue (i hear it connect but no audio pushes to cast) with firewall completely disabled.  really at a loss but am digging around the thread on reddit to see if any of those solutions work here.  i've removed everything, cleaned up my registry using ccleaner, disabled firewall, restored registry...sort of at a loss.  the fact that i hear it connect gives me hope that it can work.  thanks for your work on this i'm sure a lot of people are really excited to be able to push all audio. happy to pitch in on payment if i can get it working.  thanks!  everything worked fine before i edited the registry and tried to move the file locations.

**Comment by matbeedotcom** [comment]
Please verify this is still an issue by testing https://github.com/acidhax/chromecast-audio-stream/releases/download/0.3/audio-cast-win32-ia32.zip
